// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9KEYAZUTvUXUaEzLNb_VOru9KVE2CXg0',
    appId: '1:638564581387:web:ac5e819b4b5e7be893470e',
    messagingSenderId: '638564581387',
    projectId: 'emailauthentication-78e0b',
    authDomain: 'emailauthentication-78e0b.firebaseapp.com',
    storageBucket: 'emailauthentication-78e0b.firebasestorage.app',
    measurementId: 'G-0YG0Q9C2XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJbitWuCiBY9fLP03GfUreNMThxAV1e94',
    appId: '1:638564581387:android:5a3e32a43c1db6d693470e',
    messagingSenderId: '638564581387',
    projectId: 'emailauthentication-78e0b',
    storageBucket: 'emailauthentication-78e0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7KY13NhOlf0KSKg1CMksCV-khoYDfWd0',
    appId: '1:638564581387:ios:c61de769dfc5a7be93470e',
    messagingSenderId: '638564581387',
    projectId: 'emailauthentication-78e0b',
    storageBucket: 'emailauthentication-78e0b.firebasestorage.app',
    iosBundleId: 'com.example.usaerPannel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7KY13NhOlf0KSKg1CMksCV-khoYDfWd0',
    appId: '1:638564581387:ios:c61de769dfc5a7be93470e',
    messagingSenderId: '638564581387',
    projectId: 'emailauthentication-78e0b',
    storageBucket: 'emailauthentication-78e0b.firebasestorage.app',
    iosBundleId: 'com.example.usaerPannel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9KEYAZUTvUXUaEzLNb_VOru9KVE2CXg0',
    appId: '1:638564581387:web:d24853ac2945618e93470e',
    messagingSenderId: '638564581387',
    projectId: 'emailauthentication-78e0b',
    authDomain: 'emailauthentication-78e0b.firebaseapp.com',
    storageBucket: 'emailauthentication-78e0b.firebasestorage.app',
    measurementId: 'G-BZBGZGX5F7',
  );
}
